AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # As per VGG16 model
BATCH_SIZE: 16
INCLUDE_TOP: False 
EPOCHS: 2
CLASSES: 2
WEIGHTS: imagenet # Check model params on keras doc for model VGG16
LEARNING_RATE: 0.02 # Added all the params for model 
