artifacts_root: artifacts 
# This is for saving the data in given dir from gdrive
data_ingestion: # Only change 
  root_dir: artifacts/data_ingestion
  source_URL: "https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

   
# Now we will prepare our base model
prepare_base_model:
  root_dir: artifacts/prepare_base_model # Root dir for models
  base_model_path: artifacts/prepare_base_model/base_model.h5 # Get base model from keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 # After tuning our model

# This will be our training pipeline
training:
  root_dir: artifacts/training # Here in artifact I will create another folder training
  trained_model_path: artifacts/training/model.h5 # In training I will save my trained model